com:
	g++ tests.cpp -o tests -std=c++11  -lboost_unit_test_framework -lboost_system -lboost_serialization -pthread
	./tests


    g++ servers/server_pthread.cpp -o servers/server_pthread -std=c++11 -lboost_system -lboost_serialization -pthread
